# TDA Hyperparameters for ImageNet

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 2.0
  beta: 5.0 

# --- Negative Cache Configuration ---
negative:
  enabled: True
  shot_capacity: 1
  alpha: 0.117
  beta: 1.0
  entropy_threshold:
    lower: 0.2
    upper: 0.5 
  mask_threshold:
    lower: 0.03
    upper: 1.0

# --- Adverse Cache Configuration ---
adverse:
  enabled: True
  shot_capacity: 2
  alpha: 0.2
  beta: 1.0
  lipschitz_threshold: 0.5
  mask_threshold:
    lower: 0.03
    upper: 1.0
  ensemble_thresholds:
    confidence: 0.75
    entropy: 1.0
    gradient_norm: 3.5
    mahalanobis: 15.0
    lid: 10.0
    feature_squeeze: 0.5